### ISSUE TITLE
The labels don't match.

### ISSUE THREAD

**Issue by alex-suminski** [Karl255/UserCSS-Styles#1]
After moving the squares, the labels don't match. See on the screenshot how the Mondays are in the top row but the label `Mon` is at the second row level. (fyi 2.03.2020 was a Monay)
<img width="977" alt="AkkarinForest__Alexander_" src="https://user-images.githubusercontent.com/30773137/109414541-ac320c00-79b3-11eb-8f23-59a86c4411f9.png">

**Comment by Karl255** [comment]
Thanks for reporting this. I've fixed it.

**Comment by qwrwed** [comment]
@Karl255 Issue is back for me: 
![image](https://user-images.githubusercontent.com/2429893/162628073-10ca1df5-b6da-4622-ac00-d70bcc94b27e.png)

**Comment by Karl255** [comment]
@qwrwed Thanks for the report, it is fixed now.
